Repository dong-baeb/dong-baeb-back, pull requests merged in 2024-08, with the labels that each got.

#9 <fix> gradle-wrapper.jar 파일이 없어 빌드가 되지 않는 문제 해결
  gradle/wrapper/gradle-wrapper.jar
Labels: bug

#5 <chore> yml에 있는 민감한 정보들을 환경변수로 관리
  .gitignore
  src/main/resources/application.yml
Labels: chore

#7 <chore> PR open 시 빌드 및 테스트가 성공한 경우에만 merge 가 가능하도록 구현
  .github/workflows/pr-build.yml
Labels: chore

#12 <feat> Oauth를 이용한 사용자 로그인 구현
  .github/workflows/pr-build.yml
  build.gradle
  src/main/java/com/dongbaeb/demo/auth/controller/LoginController.java
  src/main/java/com/dongbaeb/demo/auth/dto/kakao/KakaoAccessTokenResponse.java
  src/main/java/com/dongbaeb/demo/auth/dto/kakao/KakaoAccountResponse.java
  src/main/java/com/dongbaeb/demo/auth/dto/kakao/KakaoProfileResponse.java
  src/main/java/com/dongbaeb/demo/auth/dto/kakao/KakaoUserInfoResponse.java
  src/main/java/com/dongbaeb/demo/auth/infrastructure/JwtTokenProvider.java
  src/main/java/com/dongbaeb/demo/auth/infrastructure/KakaoOauthClient.java
  src/main/java/com/dongbaeb/demo/auth/service/LoginService.java
  src/main/resources/application.yml
Labels: feature

#13 <feat> 사용자 프로필 구현
  gradlew
  gradlew.bat
  src/main/java/com/dongbaeb/demo/exception/ResourceNotFoundException.java
  src/main/java/com/dongbaeb/demo/exception/RestExceptionHandler.java
  src/main/java/com/dongbaeb/demo/profile/controller/MemberController.java
  src/main/java/com/dongbaeb/demo/profile/dto/MemberRequest.java
  src/main/java/com/dongbaeb/demo/profile/dto/MemberResponse.java
  src/main/java/com/dongbaeb/demo/profile/dto/UniversityRequest.java
  src/main/java/com/dongbaeb/demo/profile/dto/UniversityResponse.java
  src/main/java/com/dongbaeb/demo/profile/entity/BaseEntity.java
  src/main/java/com/dongbaeb/demo/profile/entity/Member.java
  src/main/java/com/dongbaeb/demo/profile/entity/MemberUniversity.java
  src/main/java/com/dongbaeb/demo/profile/entity/University.java
  src/main/java/com/dongbaeb/demo/profile/repository/MemberRepository.java
  src/main/java/com/dongbaeb/demo/profile/repository/MemberUniversityRepository.java
  src/main/java/com/dongbaeb/demo/profile/repository/UniversityRepository.java
  src/main/java/com/dongbaeb/demo/profile/service/MemberService.java
Labels: feature
